# .github/workflows/python-publish.yml

name: Publish Python distributions to PyPI

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (test, prod)'
        required: true
        default: 'test'

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Initialize Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'prod'
        uses: pypa/gh-action-pypi-publish@v2
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          repository_url: https://upload.pypi.org/legacy/
